---

- name: Create directory
  file:
    path: ~/mongo_kafka
    state: directory

- name: Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: ~/mongo_kafka/docker-compose.yml
  notify:
    - Restart services

- name: Run services
  docker_compose:
    project_src: ~/mongo_kafka
    state: present